---
title: "RandomForrestSRC"
author: "Drew"
date: "2024-02-27"
output: html_document
---

```{r}
#install.packages(c("randomForestSRC"), repos = "https://www.stats.bris.ac.uk/R/")
#install.packages(c("imbalance"), repos = "https://www.stats.bris.ac.uk/R/")
```

```{r}

#library(ggplot2)
#library(gridExtra)
library(randomForestSRC)
library(caret)
library(ROSE)
library(imbalance)

```

loading data

```{r}

dead <- read.csv("results/deadInf.csv")
live <- read.csv("results/livingInf.csv")

allCells <- rbind(live, dead)
allCells$condition <- as.factor(allCells$condition)
allCells$ratioN <- (allCells[, "aliveN"] +1) / (allCells[, "deadN"] +1)
allCells <- allCells[,2:13]

str(allCells)

```

splitting data 

```{r}

data <- allCells[, c(1:7, 12)] # takign relevant preductirs 

index <- createDataPartition(data$condition, p = 0.7, list = FALSE) # taking 40% of data
trainD <- data[index, ]
testD <- data[-index, ]

sum(trainD$condition == 0)
sum(trainD$condition == 1)

```

#### standard RF 

creating model

```{r}

rfMod <- rfsrc(condition ~ ., data = trainD, perf.type = "brier")
print(rfMod)

```

evaluation 

```{r}

somin <- subsample(rfMod, verbose = T)

vimpCI <- extract.subsample(somin)$var.jk.sel.Z
vimpCI

plot.subsample(somin)

```

#### imbalanced model - RFQ

deaful options, testing with optomisation 

```{r}

set.seed(101)

## running model

rfModRFQ <- imbalanced(condition ~ ., data = trainD)

## (1) default threshold (2) directly optimized gmean threshold
th.1 <- get.imbalanced.performance(rfModRFQ)["threshold"]
th.2 <- get.imbalanced.optimize(rfModRFQ)["threshold"]

## training performance
cat("-------- train performance ---------\n")
print(rfModRFQ)
RFQeval <- as.data.frame(get.imbalanced.performance(rfModRFQ, thresh=th.1))
  names(RFQeval) <- "train"
RFQeval[,"train optimised"] <- get.imbalanced.performance(rfModRFQ, thresh=th.2)

## test performance
cat("-------- test performance ---------\n")
predRFQ <- predict(rfModRFQ, testD)
print(predRFQ)
RFQeval[,"test"] <- get.imbalanced.performance(predRFQ, thresh=th.1)
RFQeval[,"test optimised"] <- get.imbalanced.performance(predRFQ, thresh=th.2)

```

evaluation of RFQ model with and without SMOTE sampling 

```{r}

newd.50 <- mwmote(trainD, numInstances = 50, classAttr = "condition")
newd.500 <- mwmote(trainD, numInstances = 500, classAttr = "condition")

o.with.50 <- imbalanced(condition ~ ., rbind(trainD, newd.50), importance = T) 
o.with.500 <- imbalanced(condition ~ ., rbind(trainD, newd.500))
o.without <- imbalanced(condition ~ ., trainD)

print(predict(o.with.50, trainD))
print(predict(o.with.500, trainD))
print(predict(o.without, trainD))

print(predict(o.with.50, testD))
print(predict(o.with.500, testD))
print(predict(o.without, testD))

```


```{r}
plot(o.with.50)
plot(o.with.50, plots.one.page = FALSE)
vimp(o.with.50)

somin <- subsample(o.with.50, verbose = T)

vimpCI <- extract.subsample(somin)$var.jk.sel.Z
vimpCI

plot.subsample(somin)
```

```{r}

set.seed(101)

allCells$sumN <- allCells[,"aliveN"] + allCells[,"deadN"]

#dataR <- allCells[, c(1:7, 12)] # takign relevant preductirs 
#dataS <- allCells[, c(1:7, 13)]

index <- createDataPartition(allCells$condition, p = 0.7, list = FALSE) # taking 40% of data
trainD <- allCells[index, ]
testD <- allCells[-index, ]

sum(trainD$condition == 0)
sum(trainD$condition == 1)

trainR <- trainD[, c(1:7, 12)]
testR <- testD[, c(1:7, 12)]

trainS <- trainD[, c(1:7, 13)]
testS <- testD[, c(1:7, 13)]

newd.50R <- mwmote(trainR, numInstances = 50, classAttr = "condition")
newd.50S <- mwmote(trainS, numInstances = 50, classAttr = "condition")

```

```{r}

RFQsS <- imbalanced(condition ~ ., rbind(trainS, newd.50S), importance = T) 
RFQs <- imbalanced(condition ~ ., trainS, importance = T)

RFQrS <- imbalanced(condition ~ ., rbind(trainR, newd.50R), importance = T) 
RFQr <- imbalanced(condition ~ ., trainR, importance = T)

```

```{r}
print(predict(RFQsS, trainS))
print(predict(RFQsS, testS))

print(predict(RFQs, trainS))
print(predict(RFQs, testS))

print(predict(RFQrS, trainR))
print(predict(RFQrS, testR))

print(predict(RFQr, trainR))
print(predict(RFQr, testR))

```

```{r}
plot(RFQsS)
plot(RFQs)

plot(RFQrS)
plot(RFQr)
```

```{r}

th.1sS <- get.imbalanced.performance(RFQsS)["threshold"]
th.2sS <- get.imbalanced.optimize(RFQsS)["threshold"]

RFQsS <- data.frame(train = get.imbalanced.performance(RFQsS, thresh = th.1),
                        "train optimised" = get.imbalanced.performance(RFQsS, thresh = th.2),
                        test = get.imbalanced.performance(pred, thresh = th.1),
                        "test optimised" = get.imbalanced.performance(pred, thresh = th.2))
```

```{r}
RFQsS.sub <- subsample(RFQsS, verbose = T)
RFQsS.vimpCI <- extract.subsample(RFQsS.sub)$var.jk.sel.Z
RFQsS.vimpCI


RFQs.sub <- subsample(RFQs, verbose = T)
RFQs.vimpCI <- extract.subsample(RFQs.sub)$var.jk.sel.Z
RFQs.vimpCI


RFQrS.sub <- subsample(RFQrS, verbose = T)
RFQrS.vimpCI <- extract.subsample(RFQrS.sub)$var.jk.sel.Z
RFQrS.vimpCI


RFQr.sub <- subsample(RFQr, verbose = T)
RFQr.vimpCI <- extract.subsample(RFQr.sub)$var.jk.sel.Z
RFQr.vimpCI


par(mfrow = c(2,2))
plot.subsample(RFQsS.sub, main = "Sum smote")
plot.subsample(RFQs.sub, main = "Sum" )
plot.subsample(RFQrS.sub, main = "Ratio smote")
plot.subsample(RFQr.sub, main = "Ratio")

```

