---
title: "a good attempt maybe"
author: "Drew"
date: "2024-02-05"
output: html_document
---


```{r}
library(EBImage)
```

```{r}
img <- readImage("data/trial2.tif")
```

```{r}
display(img, method="browser")
```

cropping 

```{r}
imgCr = img[100:355, 100:355, 1:3]
imgCr = img

plot(imgCr)

hist(imgCr)

imgR <- getFrame(imgCr, 1)
imgG <- getFrame(imgCr, 2)

par(mfrow = c(1,2))
plot(imgR)
plot(imgG)
```

offset subtraction 

```{r}

par(mfrow = c(1,2))
plot(imgG[948:975, 325:360]*4)
plot(imgR[948:975, 325:360]*4)

osR=mean(imgR[948:975, 325:360])
osG=mean(imgG[948:975, 325:360])

imgRo <- imgR - osR
imgGo <- imgG - osG

par(mfrow = c(2,2))
plot(imgR)
plot(imgRo)
plot(imgG)
plot(imgGo)
```

making red bolder 

```{r}
imgRb <- imgRo - imgGo /2.3

par(mfrow = c(1,2))
plot(imgRb)
plot(imgCr)
```

tesing green subtractions 

```{r}
imgGb <- imgGo - imgRo / 1.2
#imgGb2 <- imgGo - thRb1

par(mfrow = c(1,3))
#plot(imgGb2)
plot(imgGb)
plot(imgCr)

```


edge detection - red only 

```{r}

k = matrix(-1, nrow = 3, ncol = 3)
k[2, 2] = 8
k

imgRbe <- EBImage::filter2(gblur(imgRb,sigma=1.5),k)
par(mfrow = c(1,2))
plot(imgCr)
plot(normalize(imgRbe))
```

edge detection - green

```{r}

k = matrix(-1, nrow = 3, ncol = 3)
k[2, 2] = 8
k

imgGbe <- EBImage::filter2(gblur(imgGb,sigma=1.5),k)
par(mfrow = c(1,2))
plot(imgCr)
plot(normalize(imgGbe))
```


adaptive thresh - red 

```{r}
thRb1 <- thresh(imgRbe, w=5, h=5, offset=0.04)
thRb2 <- thresh(imgRbe, w=5, h=5, offset=0.036)
thRb3 <- thresh(imgRbe, w=5, h=5, offset=0.033)

par(mfrow = c(1,3))
plot(imgRb)
plot(thRb1)
plot(imgCr *2)

par(mfrow = c(1,3))
plot(imgRb)
plot(thRb2)
plot(imgCr *2)

par(mfrow = c(1,3))
plot(imgRb)
plot(thRb3)
plot(imgCr *2)

```

adaptive thresh - green 

```{r}
thGb1 <- thresh(imgGbe, w=5, h=5, offset=0.05)
thGb2 <- thresh(imgGbe, w=5, h=5, offset=0.025)
thGb3 <- thresh(imgGbe, w=5, h=5, offset=0.02)

par(mfrow = c(1,3))
plot(imgGb)
plot(thGb1)
plot(imgCr *2)

par(mfrow = c(1,3))
plot(imgGb)
plot(thGb2)
plot(imgCr *2)

par(mfrow = c(1,3))
plot(imgGb)
plot(thGb3)
plot(imgCr *2)

```

```{r}

Rlab <- bwlabel(thRb1)
Glab <- bwlabel(thGb2)

plot(thRb1)
plot(thGb2)

RedCells <- computeFeatures.moment(Rlab)
GreenCells <- computeFeatures.moment(Glab)

```






experimental shite 

```{r}
plot(colorLabels(nmaske2))
plot(thRb1)
plot(imgGat3e2)

green_o <- imgGat3e2 - thRb1

plot(green_o)
```

```{r}
AllLab <- bwlabel(imgGat3e2)
RedLab <- bwlabel(thRb1)
plot(test)


image1 <- imgGat3e2
image2 <- thRb1


label_image1 <- bwlabel(image1)

# Label connected components in image2
label_image2 <- bwlabel(image2)

# Identify the labels of dead cells in image2
dead_cell_labels <- unique(label_image2[image2 > 0])

# Remove dead cells from image1
for (label in dead_cell_labels) {
  # Set corresponding connected component in image1 to 0
  image1[label_image1 == label] <- 0
}

# Display or save the modified image1
display(image1)
```

