---
title: "colour_seperation"
author: "Drew"
date: "2024-01-29"
output: html_document
---

```{r}
library(EBImage)
```

```{r}
img <- readImage("data/trial2.tif")
```

```{r}
display(img, method="browser")
```

cropping 

```{r}
imgCr = img[100:355, 100:355, 1:3]

plot(imgCr)

hist(imgCr)

imgR <- getFrame(imgCr, 1)
imgG <- getFrame(imgCr, 2)

par(mfrow = c(1,2))
plot(imgR)
plot(imgG)
```

offset subtraction 

```{r}

par(mfrow = c(1,2))
plot(imgR[110:120, 82:92]*2)
plot(imgG[110:120, 82:92]*2)

osR=mean(imgR[110:120, 82:92])
osG=mean(imgG[110:120, 82:92])

imgRo <- imgR - osR
imgGo <- imgG - osG

par(mfrow = c(2,2))
plot(imgR)
plot(imgRo)
plot(imgG)
plot(imgGo)
```

```{r}
par(mfrow = c(2,2))
plot(imgCr)
plot(imgRo)
plot(imgGo)
```

```{r}
par(mfrow = c(1,2))
plot(imgCr[145:175, 185:215, 1:3]*2)
plot(imgRo[145:175, 185:215]*2)
```

```{r}
Rc <- imgRo[145:160, 190:205]
Gc <- imgGo[145:160, 190:205]
Ic <- imgCr[145:160, 190:205, 1:3]

RcDat <- Rc@.Data
GcDat <- Gc@.Data

par(mfrow = c(2,2))
plot(Rc)
plot(Ic)
plot(Gc)
```

