---
title: "watershed"
author: "Drew"
date: "2024-01-13"
output: html_document
---

```{r}
library(EBImage)
```

```{r}
img <- readImage("data/trial2.tif")
```

```{r}
display(img, method="browser")

```

increasing contrast and gamma 

```{r}
#imgB <- img - 0.1
imgG <- (img * 1.5) ^ 1.5
imgG = imgG[100:300, 100:300, 1:3]
imgG <- (img * 2) ^ 1.2
imgG2 = imgG2[100:300, 100:300, 1:3]

plot(imgG)
plot(imgG2)

# display(imgB, method="browser")
display(imgC, method="browser")
display(imgG, method="browser")

imgCr = img[100:300, 100:300, 1:3]
plot(imgCr)
imgG = imgG[100:300, 100:300, 1:3]
plot(imgG)
```

sharpennign edges 

```{r}

imgB <- img
colorMode(imgB) = Grayscale

nuc_gblur = gblur(imgG, sigma = 1)
plot(nuc_gblur)
display(nuc_gblur, all=TRUE )


fhi = matrix(1, nrow = 3, ncol = 3)
fhi[2, 2] = -8

img_fhi = filter2(imgG, k)
plot(img_fhi)

k = matrix(-1, nrow = 3, ncol = 3)
k[2, 2] = 8
k
Geimg=EBImage::filter2(gblur(imgG,sigma=1),k)
display(Geimg, method="browser")

display(img_fhi)

nfilt <- medianFilter(imgG, 3) # shit
plot(nfilt)

imgB <- imgG
colorMode(imgB) = Grayscale
Gth <- otsu(imgB) # not working 
Gthresh <- imgGbase > Gth 
display(Gthresh, method="browser")

```


splitting

```{r}

img1 <- getFrame(imgG, 1)
img2 <- getFrame(imgG, 2)
img3 <- getFrame(imgG, 3)

display(img1, method="browser")
display(img2, method="browser")
display(img3, method="browser")

```


```{r}
k = matrix(-1, nrow = 3, ncol = 3)
k[2, 2] = 8
k
Geimg = EBImage::filter2(gblur(imgG,sigma=1),k)

test <- Geimg * 2 

par(mfrow = c(1,2))
plot(test)
plot(imgG)


test <- Geimg * 2
plot(test)
```


### thresholding

using thresh function which creates little box and adaptivley thresholds across image so accounts for varying frequency across image 

```{r}

colorMode(test) = Grayscale
imgG

display(thresh(test, w=10, h=10, offset=0.025), all=TRUE )

ATimg1 <- thresh(test, w=5, h=5, offset=0.1)
ATimg0.5 <- thresh(imgG, w=5, h=5, offset=0.05)
ATimg0.25 <- thresh(imgG, w=5, h=5, offset=0.025)

par(mfrow = c(2,2))
plot(imgG, all = T)
plot(ATimg1, all = T)
plot(ATimg0.5)
plot(ATimg0.25)

display(ATimg, method="browser")

ATimg0.25

```

```{r}


img1 <- getFrame(ATimg0.25, 1)
img2 <- getFrame(ATimg0.25, 2)
img3 <- getFrame(ATimg0.25, 3)

display(img1, method="browser")
display(img2, method="browser")
display(img3, method="browser")

par(mfrow = c(2,1))
plot(img1)
plot(img2)

```

```{r}
nmask = watershed( distmap(ATimg1), tolerance = 1, ext = 1)
display(colorLabels(nmask), all=TRUE)

par(mfrow = c(1,2))
plot(imgG)
plot(colorLabels(nmask))
```









using filter2 

these just apply blur - not particullary usefull 

```{r}
f = makeBrush(21, shape='disc', step=FALSE)
display(f, title='Disc filter')
f = f/sum(f)
y = filter2(imgG, f)
display(y, title='Filtered image')
```

```{r}
y = filter2(imgG, f, boundary=c(0,.5,1))
  display(y, title='Filtered image with linear padded boundary')
```

```{r}
 la = matrix(1, nc=3, nr=3)
  la[2,2] = -8
  y = filter2(imgGo, la)
  display(y, title='Filtered image')
```

```{r}
y = filter2(imgG, la, boundary='replicate')
  display(y, title='Filtered image with replicated boundary')
```

